name: Code Review Assistant
on:
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  process-review:
    if: |
      (github.event_name == 'pull_request_review' && github.event.review.state == 'changes_requested') ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@cloi'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref || github.event.issue.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Cloi globally
        run: npm install -g .

      - name: Get PR information
        id: pr-info
        run: |
          if [[ "${{ github.event_name }}" == "pull_request_review" ]]; then
            PR_NUMBER=${{ github.event.pull_request.number }}
          else
            PR_NUMBER=${{ github.event.issue.number }}
          fi
          
          echo "pr-number=${PR_NUMBER}" >> $GITHUB_OUTPUT
          
          # Get PR details
          gh pr view ${PR_NUMBER} --json number,title,body,reviews,comments > pr-details.json
          
          # Get changed files
          gh pr diff ${PR_NUMBER} --name-only > changed-files.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract review comments
        id: extract-comments
        run: |
          # Extract review comments and feedback
          if [[ "${{ github.event_name }}" == "pull_request_review" ]]; then
            # Extract from review event
            cat > review-context.json << EOF
          {
            "trigger": "code-review",
            "prNumber": ${{ steps.pr-info.outputs.pr-number }},
            "reviewComments": [
              {
                "author": "${{ github.event.review.user.login }}",
                "body": "${{ github.event.review.body }}",
                "state": "${{ github.event.review.state }}",
                "timestamp": "${{ github.event.review.submitted_at }}"
              }
            ],
            "repository": "${{ github.repository }}",
            "local": false
          }
          EOF
          else
            # Extract from comment mentioning @cloi
            cat > review-context.json << EOF
          {
            "trigger": "code-review",
            "prNumber": ${{ steps.pr-info.outputs.pr-number }},
            "reviewComments": [
              {
                "author": "${{ github.event.comment.user.login }}",
                "body": "${{ github.event.comment.body }}",
                "type": "comment",
                "timestamp": "${{ github.event.comment.created_at }}"
              }
            ],
            "repository": "${{ github.repository }}",
            "local": false
          }
          EOF
          fi
          
          # Add changed files to context
          jq --rawfile files changed-files.txt '. + {changedFiles: ($files | split("\n") | map(select(length > 0)))}' review-context.json > review-context-updated.json
          mv review-context-updated.json review-context.json

      - name: Run Code Review Workflow
        id: code-review
        run: |
          # Run the code review workflow
          cloi workflow run code-review \
            --context review-context.json \
            --comments-file pr-details.json || echo "Code review workflow completed with issues"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "changes-made=false" >> $GITHUB_OUTPUT
            echo "No changes were made by the code review workflow"
          else
            echo "changes-made=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
            git diff --name-only > changed-by-cloi.txt
          fi

      - name: Commit and push changes
        if: steps.check-changes.outputs.changes-made == 'true'
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "Cloi Auto-Review"
          
          # Commit changes
          git add .
          git commit -m "🤖 Apply code review feedback

          Automatically applied changes based on code review feedback:
          $(cat changed-by-cloi.txt | head -10)
          
          Generated by Cloi Code Review Assistant"
          
          # Push changes
          git push origin HEAD

      - name: Comment on PR
        if: steps.check-changes.outputs.changes-made == 'true'
        run: |
          gh pr comment ${{ steps.pr-info.outputs.pr-number }} --body "🤖 **Code Review Feedback Applied**

          I've automatically applied changes based on the code review feedback.

          **Changes made:**
          $(cat changed-by-cloi.txt | sed 's/^/- /' | head -10)

          **Review feedback processed:**
          - ${{ github.event.review.user.login || github.event.comment.user.login }}: \"$(echo '${{ github.event.review.body || github.event.comment.body }}' | head -c 100)...\"

          Please review these automated changes. If they look good, the PR should be ready for approval!

          Generated by [Cloi Code Review Assistant](https://github.com/tosin2013/cloi)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment if no changes needed
        if: steps.check-changes.outputs.changes-made == 'false'
        run: |
          gh pr comment ${{ steps.pr-info.outputs.pr-number }} --body "🤖 **Code Review Analysis Complete**

          I've analyzed the code review feedback but didn't find any changes that I could automatically apply.

          **Review feedback:**
          - ${{ github.event.review.user.login || github.event.comment.user.login }}: \"$(echo '${{ github.event.review.body || github.event.comment.body }}' | head -c 100)...\"

          The feedback may require manual implementation or could be addressing design/architectural considerations that need human judgment.

          Generated by [Cloi Code Review Assistant](https://github.com/tosin2013/cloi)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Handle workflow failure
        if: failure()
        run: |
          gh pr comment ${{ steps.pr-info.outputs.pr-number }} --body "🚨 **Code Review Assistant Error**

          I encountered an error while trying to process the code review feedback.

          **Review feedback:**
          - ${{ github.event.review.user.login || github.event.comment.user.login }}: \"$(echo '${{ github.event.review.body || github.event.comment.body }}' | head -c 100)...\"

          Please check the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.

          You can also try running the code review workflow manually:
          \`\`\`bash
          cloi workflow run code-review --pr ${{ steps.pr-info.outputs.pr-number }}
          \`\`\`"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}