name: Security Scan
on:
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  security:
    if: false  # Temporarily disabled to focus on cloi-auto-repair.yml testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cloi
        run: npm install -g @cloi/cli

      - name: Run npm audit
        run: npm audit || echo "Security issues found"

      - name: Run security scan
        run: |
          cloi workflow run security-scan \
            --context '{"type": "nodejs", "packageManager": "npm"}'

      - name: Upload security results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-results
          path: security-results.json
          retention-days: 90